# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "cbor-1.0.0-RcQE_AswAQAPlqBCZXYQf9DZXn-0Ubt8Mk03ZcJWcsAG";
    path = fetchgit {
      url = "https://github.com/neurocyte/cbor";
      rev = "7d2eeb68c8a2fb3f4d6baad6cc04c521b92974c0";
      hash = "sha256-EWOz+BPxRB5NxmqNzrJcdcaoGH6PdgeU4KI9IjJqar8=";
    };
  }
  {
    name = "clap-0.11.0-oBajB-HnAQDPCKYzwF7rO3qDFwRcD39Q0DALlTSz5H7e";
    path = fetchzip {
      url = "https://github.com/Hejsil/zig-clap/archive/refs/tags/0.11.0.tar.gz";
      hash = "sha256-XytqwtoE0xaR43YustgK68sAQPVfC0Dt+uCs8UTfkbU=";
    };
  }
  {
    name = "flow_syntax-0.6.0-X8jOoWgVAQBSMU8XHKJgDibqPeo0i3NzXl7GEnSLIzb6";
    path = fetchgit {
      url = "https://github.com/neurocyte/flow-syntax";
      rev = "d6e867378babfd899486547b6e59bf7863f6097e";
      hash = "sha256-S4sMDhpoXDSOYlin9t67Nvstss+6fE6YtAaBDlJKLNQ=";
    };
  }
  {
    name = "tree_sitter-0.22.4-150-g7e3f5726-z0LhyGeG1y67PeOltaplVkxRNT2jMMexQhbUlrh0vdxM";
    path = fetchzip {
      url = "https://github.com/neurocyte/tree-sitter/releases/download/master-6e2827ee231e220467bf04d2a2746faff5cb204a/source.tar.gz";
      hash = "sha256-ngXLB8iQqHqVgW7GN5kupri+UUla6KwkVC42a0wkCto=";
    };
  }
  {
    name = "uucode-0.1.0-ZZjBPj96QADXyt5sqwBJUnhaDYs_qBeeKijZvlRa0eqM";
    path = fetchgit {
      url = "https://github.com/jacobsandlund/uucode";
      rev = "5f05f8f83a75caea201f12cc8ea32a2d82ea9732";
      hash = "sha256-sHPh+TQSdUGus/QTbj7KSJJkTuNTrK4VNmQDjS30Lf8=";
    };
  }
  {
    name = "vaxis-0.5.1-BWNV_Bw_CQAIVNh1ekGVzbip25CYBQ_J3kgABnYGFnI4";
    path = fetchgit {
      url = "https://github.com/rockorager/libvaxis.git";
      rev = "8a9c2d5e1b3778f1ea43c9bd5d325cfa72016584";
      hash = "sha256-d1sU1jwx8dmRsldE269ERlyw1Qaf7BkRQF7X5DyiFeg=";
    };
  }
  {
    name = "zigimg-0.1.0-8_eo2vUZFgAAtN1c6dAO5DdqL0d4cEWHtn6iR5ucZJti";
    path = fetchgit {
      url = "https://github.com/zigimg/zigimg";
      rev = "eab2522c023b9259db8b13f2f90d609b7437e5f6";
      hash = "sha256-e42T/ZmRzuzWAhwWkcWScukcOd6rNZ1VK1wk0XGTVKs=";
    };
  }
]
